### ISSUE TITLE
[Site] Error 404 ou o erro de página não encontrada

### ISSUE THREAD

**Issue by andrefs9** [ricardodacp/explicame.pt#11]
Sempre que aparecer estes erros na página é possível colocar uma mensagem de que estamos em manutenção à plataforma, pedindo desculpa pelo incómodo?

**Comment by ricardodacp** [comment]
Esse erro acontece porque foste a um URL que não existe e essa é a página default para esses casos. O que podemos é fazer com que todos os urls que não existam, reencaminhem para a homepage

**Comment by andrefs9** [comment]
Yaya, faz sentido fazer isso, encaminhar para a home.

Mas o que me referia é por exemplo quando o site está em baixo, por exemplo manutenção. É possível colocar uma mensagem deste género?

**Comment by andrefs9** [comment]
Exemplo! Há utilizadores que vêm parar a páginas como esta, directamente do Google:
https://www.explicame.pt/room-type/apoio-em-trabalhos-academicos/

**Comment by andrefs9** [comment]
Sim é melhor redirecionar tudo para Homepage não achas?

**Comment by ricardodacp** [comment]
Concordo. Done!

**Comment by andrefs9** [comment]
Continuam a haver erros 404:

https://www.whatatutor.com/?page_id=25584 que surge na sequência de https://www.whatatutor.com/locais-de-estudo/lisboa-locais-de-estudo/

Não existe nenhum plugin que nos ajuda a melhorar o design da página de erro 404?
