### ISSUE TITLE
[Blog] Navbar

### ISSUE THREAD

**Issue by andrefs9** [ricardodacp/explicame.pt#20]
Consegues mover a caixa de pesquisa para baixo, de modo a que consigamos adicionar mais categorias à navbar, e que as mesmas fiquem na mesma linha?

![image](https://user-images.githubusercontent.com/45218048/49392377-22d4f600-f726-11e8-82e7-5f3f27be9a36.png)

**Comment by ricardodacp** [comment]
Não é assim que funciona, a sidebar não "rouba" espaço aos elementos do blog, são dois blocos independentes que estão lado a lado. Para fazer o que querias, teria que ser acima da página, no tema e ia aparecer em todas as páginas. Ainda não tenho nenhuma solução melhor para esse problema...

**Comment by andrefs9** [comment]
Ok, penso que com as categorias que estão pensados já não haverá problema! ;)

**Comment by ricardodacp** [comment]
Vou então fechar o issue por agora
