### ISSUE TITLE
[Site] URL da Explicame.pt com slugs 

### ISSUE THREAD

**Issue by andrefs9** [ricardodacp/explicame.pt#21]
Ricardo também consegue reencaminhar para homepage ou para uma página específica este tipo de url da explicame.pt que tem diferentes slugs e que leva o utilizador para página não encontradas?

![image](https://user-images.githubusercontent.com/45218048/49441462-6da24c80-f7be-11e8-87d3-f11d05062501.png)

**Comment by ricardodacp** [comment]
Eu acho que não consigo fazer redirects do url `https://www.explicame.pt/...` porque já não é o domínio oficial, Isso talvez seja possível no mesmo local onde foi gerido o domínio

**Comment by andrefs9** [comment]
Hum, então onde poderei ver e fazer isso?

**Comment by andrefs9** [comment]
@ricardodacp podemos priorizar este ticket, por favor?
