### ISSUE TITLE
[Site] É possível colocar mais um título no Header do site?

### ISSUE THREAD

**Issue by andrefs9** [ricardodacp/explicame.pt#24]
Colocar mais um botão (com o nome: "Quero Explicador") no Header do Site a encaminhar os utilizadores para a seguinte página: https://www.whatatutor.com/?post_type=accommodation&date_from=

![image](https://user-images.githubusercontent.com/45218048/49656289-df83cb80-fa34-11e8-8f69-e58ff2331221.png)

**Comment by ricardodacp** [comment]
Contando com aquele que foi escondido, não vai caber sem apertar ao máximo e diminuir tamanhos de letra

**Comment by ricardodacp** [comment]
Penso que isto foi o que se fez há uns dias
