### ISSUE TITLE
[SITE] Adicionar mais um hiperlink e imagem em "Reconhecimentos e Prémios"

### ISSUE THREAD

**Issue by andrefs9** [ricardodacp/explicame.pt#26]
Hiperlink: https://joom.ag/Oc5a/p38
Imagem: assim que tiver deixo aqui

E adicionar também este.
Não tem Hiperlink ainda.
Só imagem (não coloquei a imagem no formato e tamanho específico para esta seção)
![yan-seal-red-por](https://user-images.githubusercontent.com/45218048/50256303-909f4400-03ed-11e9-979e-94a0c90b1d14.png)

NOTA: POR FAVOR DEIXA NO COMENTÁRIO O TAMANHO DA IMAGEM PARA ESTA SECÇÃO, DE MODO A QUE REGISTE NAS MINHAS CÁBULAS PFF

**Comment by ricardodacp** [comment]
Não me lembro de termos definido medidas fixas aqui, mas dei um comprimento de 150px com largura automatica proporcional.
