### ISSUE TITLE
[Domínio] Tornar whatatutor.com o site principal

### ISSUE THREAD

**Issue by andrefs9** [ricardodacp/explicame.pt#4]
Pesquisar sobre como mudar domínio wordpress e webhs.

**Comment by andrefs9** [comment]
A WEB HS diz que nos ajuda a fazer a transição de qual o domínio principal:

"Confirmamos a possibilidade de realizar a alteração em causa. Permita-nos fazer a ressalva que será posteriormente necessário realizar as devidas alterações na plataforma de website que se encontra a utilizar (wordpress) por forma a que o endereço base / associado aos conteúdos seja também actualizado para o whatatutor.com - Assim queira indicar-nos quando pretende que façamos a alteração do domínio principal da conta."

Sabes o que temos que fazer do nosso lado, no wordpress?

**Comment by ricardodacp** [comment]
Suponho que seja ir aos settings do wordpress mudar os URL's que dizem `https://www.explicame.pt/`

**Comment by andrefs9** [comment]
Esperemos que seja assim tão fácil. Queres combinar um dia e hora para procedermos a esta alteração, conjuntamente com a WEB HS?

**Comment by ricardodacp** [comment]
Sim, acho que o melhor é me dizerem uma hora e eu adapto-me para conseguir e caso não possa mesmo, arranja-se outra hora

**Comment by andrefs9** [comment]
Tens preferência por manhãs ou tardes, por volta de que horas?
