### ISSUE TITLE
[Blog] Tamanho Imagens de Artigos em Lista

### ISSUE THREAD

**Issue by andrefs9** [ricardodacp/explicame.pt#6]
Ou é meu atrofio ou não sei, mas penso que coloquei a imagem que deixo em anexo no tamanho correcto. Podes dar uma olhada por favor e voltar a reforçar o tamanho, caso esteja errado?

![aaa](https://user-images.githubusercontent.com/45218048/48903156-a5ba9e80-ee52-11e8-8516-33e222a699eb.png)

**Comment by ricardodacp** [comment]
Este issue ainda está por resolver ou já ficou bem com as mudanças que foram feitas da última vez?
