### ISSUE TITLE
[Site] Páginad e Registo

### ISSUE THREAD

**Issue by andrefs9** [ricardodacp/explicame.pt#7]
Eliminar o logótipo que está evidenciado a vermelho.
Aumentar o tamanho do logótipo que está evidenciado a azul.

![aaa](https://user-images.githubusercontent.com/45218048/48904568-b4a35000-ee56-11e8-9f58-ae5c08b365c1.JPG)

**Comment by ricardodacp** [comment]
@andrefs9 Já tirei o logo do canto superior direito, mas ao aumentar o logo do centro, perde bastante qualidade porque o logo tem exatamente o tamanho definido para aquele espaço.

**Comment by andrefs9** [comment]
Caga, mantém o tamanho do logo então! Ou preferes que te envie a imagem num tamanho superior?

**Comment by ricardodacp** [comment]
O problema é que essa é a mesma no resto do site, por isso ia afetar a navbar da homepage
